"""agrega handle pronombres e insignia al perfil

Revision ID: 05050fb65d0c
Revises: d6133645dc7b
Create Date: 2026-08-25 16:59:17.701733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '05050fb65d0c'
down_revision: Union[str, None] = 'd6133645dc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pronombres', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('insignia', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('insignia')
        batch_op.drop_column('pronombres')
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
