"""agrega emojis personalizados

Revision ID: 08c9421a656c
Revises: 05050fb65d0c
Create Date: 2026-08-25 17:41:19.206302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08c9421a656c'
down_revision: Union[str, None] = '05050fb65d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emojis_personalizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emojis_personalizados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emojis_personalizados_nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emojis_personalizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emojis_personalizados_nombre'))

    op.drop_table('emojis_personalizados')
    # ### end Alembic commands ###
