"""agrega nota_bookmark a fics

Revision ID: 096c739a75bc
Revises: 2959a5f79e55
Create Date: 2026-08-25 13:39:20.626896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '096c739a75bc'
down_revision: Union[str, None] = '2959a5f79e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_bookmark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.drop_column('nota_bookmark')

    # ### end Alembic commands ###
