"""agrega tabla novedades

Revision ID: 2959a5f79e55
Revises: 4ba72ab913f7
Create Date: 2026-08-25 12:12:12.079476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2959a5f79e55'
down_revision: Union[str, None] = '4ba72ab913f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('capitulos_publicados', sa.Integer(), nullable=False),
    sa.Column('detectado_en', sa.DateTime(), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novedades_detectado_en'), ['detectado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_novedades_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novedades_leida'), ['leida'], unique=False)
        batch_op.create_index(batch_op.f('ix_novedades_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novedades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_novedades_tipo'))
        batch_op.drop_index(batch_op.f('ix_novedades_leida'))
        batch_op.drop_index(batch_op.f('ix_novedades_fic_id'))
        batch_op.drop_index(batch_op.f('ix_novedades_detectado_en'))

    op.drop_table('novedades')
    # ### end Alembic commands ###
