"""agrega gifs personalizados al perfil

Revision ID: 33da372ffc67
Revises: 08c9421a656c
Create Date: 2026-08-26 10:31:33.019585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '33da372ffc67'
down_revision: Union[str, None] = '08c9421a656c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gif1_ruta', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gif2_ruta', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gif3_ruta', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('gif3_ruta')
        batch_op.drop_column('gif2_ruta')
        batch_op.drop_column('gif1_ruta')

    # ### end Alembic commands ###
