"""agrega nombre_usuario y bio a perfil_config

Revision ID: 40e26b7cd9e3
Revises: 096c739a75bc
Create Date: 2026-08-25 14:25:51.182417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40e26b7cd9e3'
down_revision: Union[str, None] = '096c739a75bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_usuario', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('nombre_usuario')

    # ### end Alembic commands ###
