"""agrega posicion de recorte a avatar y portada

Revision ID: 4ba72ab913f7
Revises: 797268f23b09
Create Date: 2026-08-25 10:50:58.054057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ba72ab913f7'
down_revision: Union[str, None] = '797268f23b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('avatar_posicion', sa.String(length=20), nullable=False, server_default='50% 50%')
        )
        batch_op.add_column(
            sa.Column('portada_posicion', sa.String(length=20), nullable=False, server_default='50% 50%')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('portada_posicion')
        batch_op.drop_column('avatar_posicion')

    # ### end Alembic commands ###
