"""agrega idioma a fics y favoritos_destacados a perfil_config

Revision ID: 797268f23b09
Revises: fb5ac79abbc0
Create Date: 2026-08-25 10:18:19.358353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '797268f23b09'
down_revision: Union[str, None] = 'fb5ac79abbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idioma', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_fics_idioma'), ['idioma'], unique=False)

    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favoritos_destacados', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('favoritos_destacados')

    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fics_idioma'))
        batch_op.drop_column('idioma')

    # ### end Alembic commands ###
