"""etiquetas personales

Revision ID: 9a88995b9e9a
Revises: e1fa7f24592e
Create Date: 2026-08-20 18:12:20.358172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a88995b9e9a'
down_revision: Union[str, None] = 'e1fa7f24592e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas_personales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etiquetas_personales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etiquetas_personales_nombre'), ['nombre'], unique=True)

    op.create_table('fic_etiquetas_personales',
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas_personales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'etiqueta_id')
    )
    with op.batch_alter_table('fic_etiquetas_personales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fic_etiquetas_personales_etiqueta_id'), ['etiqueta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fic_etiquetas_personales_fic_id'), ['fic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fic_etiquetas_personales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fic_etiquetas_personales_fic_id'))
        batch_op.drop_index(batch_op.f('ix_fic_etiquetas_personales_etiqueta_id'))

    op.drop_table('fic_etiquetas_personales')
    with op.batch_alter_table('etiquetas_personales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etiquetas_personales_nombre'))

    op.drop_table('etiquetas_personales')
    # ### end Alembic commands ###
