"""perfil_favoritos_y_cita

Revision ID: a0c9265073f2
Revises: cafd6c73bf05
Create Date: 2026-08-24 17:52:42.527513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0c9265073f2'
down_revision: Union[str, None] = 'cafd6c73bf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fic_id')
    )
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cita_texto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cita_fuente', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_config', schema=None) as batch_op:
        batch_op.drop_column('cita_fuente')
        batch_op.drop_column('cita_texto')

    op.drop_table('perfil_favoritos')
    # ### end Alembic commands ###
