"""agrega imagenes a resenas

Revision ID: a9a2497c939f
Revises: 33da372ffc67
Create Date: 2026-10-01 10:33:28.478961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9a2497c939f'
down_revision: Union[str, None] = '33da372ffc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resena_imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resena_id', sa.Integer(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resena_id'], ['resenas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resena_imagenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resena_imagenes_resena_id'), ['resena_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena_imagenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resena_imagenes_resena_id'))

    op.drop_table('resena_imagenes')
    # ### end Alembic commands ###
