"""perfil_config

Revision ID: cafd6c73bf05
Revises: 9a88995b9e9a
Create Date: 2026-08-24 16:40:57.764123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cafd6c73bf05'
down_revision: Union[str, None] = '9a88995b9e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar_ruta', sa.String(length=500), nullable=True),
    sa.Column('portada_ruta', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_config')
    # ### end Alembic commands ###
