"""agrega listas de recomendaciones

Revision ID: d6133645dc7b
Revises: 882b8104ac72
Create Date: 2026-08-25 16:18:04.820996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6133645dc7b'
down_revision: Union[str, None] = '882b8104ac72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listas_recomendadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listas_recomendadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listas_recomendadas_token'), ['token'], unique=True)

    op.create_table('lista_recomendada_fics',
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_recomendadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lista_id', 'fic_id')
    )
    with op.batch_alter_table('lista_recomendada_fics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lista_recomendada_fics_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lista_recomendada_fics_lista_id'), ['lista_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista_recomendada_fics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lista_recomendada_fics_lista_id'))
        batch_op.drop_index(batch_op.f('ix_lista_recomendada_fics_fic_id'))

    op.drop_table('lista_recomendada_fics')
    with op.batch_alter_table('listas_recomendadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listas_recomendadas_token'))

    op.drop_table('listas_recomendadas')
    # ### end Alembic commands ###
