"""esquema inicial

Revision ID: e1fa7f24592e
Revises: 
Create Date: 2026-08-18 14:37:45.380524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e1fa7f24592e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fandoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fandoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fandoms_nombre'), ['nombre'], unique=True)

    op.create_table('fics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ao3_id', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('autor_url', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('chapters_published', sa.Integer(), nullable=False),
    sa.Column('chapters_total', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.String(length=30), nullable=True),
    sa.Column('categorias', sa.String(length=255), nullable=True),
    sa.Column('warnings', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=True),
    sa.Column('fecha_primer_import', sa.DateTime(), nullable=False),
    sa.Column('ultima_revision', sa.DateTime(), nullable=True),
    sa.Column('deleted_detected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fics_ao3_id'), ['ao3_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_fics_complete'), ['complete'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_deleted_detected_at'), ['deleted_detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_fecha_actualizacion'), ['fecha_actualizacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_fecha_primer_import'), ['fecha_primer_import'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_fecha_publicacion'), ['fecha_publicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_ultima_revision'), ['ultima_revision'], unique=False)
        batch_op.create_index(batch_op.f('ix_fics_word_count'), ['word_count'], unique=False)

    op.create_table('import_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fics_nuevos', sa.Integer(), nullable=False),
    sa.Column('fics_actualizados', sa.Integer(), nullable=False),
    sa.Column('errores', sa.Integer(), nullable=False),
    sa.Column('errores_detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_log_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_log_tipo'), ['tipo'], unique=False)

    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personajes_nombre'), ['nombre'], unique=True)

    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ships_nombre'), ['nombre'], unique=True)

    op.create_table('tags_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags_adicionales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_adicionales_nombre'), ['nombre'], unique=True)

    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=False),
    sa.Column('ruta_local', sa.String(length=1000), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('tamano', sa.Integer(), nullable=False),
    sa.Column('fecha_descarga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fic_id', 'formato', name='uq_archivo_fic_formato')
    )
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archivos_fecha_descarga'), ['fecha_descarga'], unique=False)
        batch_op.create_index(batch_op.f('ix_archivos_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archivos_hash_sha256'), ['hash_sha256'], unique=False)

    op.create_table('coleccion_fics',
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coleccion_id', 'fic_id')
    )
    with op.batch_alter_table('coleccion_fics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coleccion_fics_coleccion_id'), ['coleccion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coleccion_fics_fic_id'), ['fic_id'], unique=False)

    op.create_table('fic_fandoms',
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('fandom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'fandom_id')
    )
    with op.batch_alter_table('fic_fandoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fic_fandoms_fandom_id'), ['fandom_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fic_fandoms_fic_id'), ['fic_id'], unique=False)

    op.create_table('fic_personajes',
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['personaje_id'], ['personajes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'personaje_id')
    )
    with op.batch_alter_table('fic_personajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fic_personajes_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fic_personajes_personaje_id'), ['personaje_id'], unique=False)

    op.create_table('fic_ships',
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'ship_id')
    )
    with op.batch_alter_table('fic_ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fic_ships_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fic_ships_ship_id'), ['ship_id'], unique=False)

    op.create_table('fic_tags_adicionales',
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags_adicionales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fic_id', 'tag_id')
    )
    with op.batch_alter_table('fic_tags_adicionales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fic_tags_adicionales_fic_id'), ['fic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fic_tags_adicionales_tag_id'), ['tag_id'], unique=False)

    op.create_table('lecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('es_relectura', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lecturas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_lecturas_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_lecturas_fic_id'), ['fic_id'], unique=False)

    op.create_table('resenas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fic_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('contiene_spoilers', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resenas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_resenas_fic_id'), ['fic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resenas_fic_id'))
        batch_op.drop_index(batch_op.f('ix_resenas_fecha'))

    op.drop_table('resenas')
    with op.batch_alter_table('lecturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lecturas_fic_id'))
        batch_op.drop_index(batch_op.f('ix_lecturas_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_lecturas_estado'))

    op.drop_table('lecturas')
    with op.batch_alter_table('fic_tags_adicionales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fic_tags_adicionales_tag_id'))
        batch_op.drop_index(batch_op.f('ix_fic_tags_adicionales_fic_id'))

    op.drop_table('fic_tags_adicionales')
    with op.batch_alter_table('fic_ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fic_ships_ship_id'))
        batch_op.drop_index(batch_op.f('ix_fic_ships_fic_id'))

    op.drop_table('fic_ships')
    with op.batch_alter_table('fic_personajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fic_personajes_personaje_id'))
        batch_op.drop_index(batch_op.f('ix_fic_personajes_fic_id'))

    op.drop_table('fic_personajes')
    with op.batch_alter_table('fic_fandoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fic_fandoms_fic_id'))
        batch_op.drop_index(batch_op.f('ix_fic_fandoms_fandom_id'))

    op.drop_table('fic_fandoms')
    with op.batch_alter_table('coleccion_fics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coleccion_fics_fic_id'))
        batch_op.drop_index(batch_op.f('ix_coleccion_fics_coleccion_id'))

    op.drop_table('coleccion_fics')
    with op.batch_alter_table('archivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archivos_hash_sha256'))
        batch_op.drop_index(batch_op.f('ix_archivos_fic_id'))
        batch_op.drop_index(batch_op.f('ix_archivos_fecha_descarga'))

    op.drop_table('archivos')
    with op.batch_alter_table('tags_adicionales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_adicionales_nombre'))

    op.drop_table('tags_adicionales')
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ships_nombre'))

    op.drop_table('ships')
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personajes_nombre'))

    op.drop_table('personajes')
    with op.batch_alter_table('import_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_log_tipo'))
        batch_op.drop_index(batch_op.f('ix_import_log_fecha'))

    op.drop_table('import_log')
    with op.batch_alter_table('fics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fics_word_count'))
        batch_op.drop_index(batch_op.f('ix_fics_ultima_revision'))
        batch_op.drop_index(batch_op.f('ix_fics_fecha_publicacion'))
        batch_op.drop_index(batch_op.f('ix_fics_fecha_primer_import'))
        batch_op.drop_index(batch_op.f('ix_fics_fecha_actualizacion'))
        batch_op.drop_index(batch_op.f('ix_fics_deleted_detected_at'))
        batch_op.drop_index(batch_op.f('ix_fics_complete'))
        batch_op.drop_index(batch_op.f('ix_fics_ao3_id'))

    op.drop_table('fics')
    with op.batch_alter_table('fandoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fandoms_nombre'))

    op.drop_table('fandoms')
    op.drop_table('colecciones')
    # ### end Alembic commands ###
