"""quita_perfil_favoritos

Revision ID: fb5ac79abbc0
Revises: a0c9265073f2
Create Date: 2026-08-24 18:14:04.672201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb5ac79abbc0'
down_revision: Union[str, None] = 'a0c9265073f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_favoritos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_favoritos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fic_id', sa.INTEGER(), nullable=False),
    sa.Column('orden', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['fic_id'], ['fics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fic_id')
    )
    # ### end Alembic commands ###
